name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Get Firefox extension version
        uses: sergeysova/jq-action@v2
        id: firefox_version
        with:
          cmd: 'jq -r .version firefox_manifest.json'

      - name: Get Chrome extension version
        uses: sergeysova/jq-action@v2
        id: chrome_version
        with:
          cmd: 'jq -r .version chrome_manifest.json'

      - name: Check extension versions
        run: |
          if [ "${{ steps.firefox_version.outputs.value }}" != "${{ steps.chrome_version.outputs.value }}" ]; then
            echo "Extension versions do not match (${{ steps.firefox_version.outputs.value }} != ${{ steps.chrome_version.outputs.value }})"
            exit 1
          fi

          if [ "refs/tags/v${{ steps.firefox_version.outputs.value }}" != "${{ github.ref }}" ]; then
            echo "Tag (${{ github.ref }}) does not match extension version (${{ steps.firefox_version.outputs.value }})"
            exit 1
          fi

      - name: Prepare for Firefox build
        run: |
          bash bin/prepare_build.sh firefox
          mkdir -p dist

      - name: Add Firefox extension id to manifest
        uses: sergeysova/jq-action@v2
        with:
          cmd: 'echo $(jq ". += {\"browser_specific_settings\": {\"gecko\": {\"id\": \"{${{ vars.FIREFOX_EXTENSION_ID }}}\"}}}" build/manifest.json) > build/manifest.json'

      - name: Firefox build
        uses: kewisch/action-web-ext@v1
        id: firefox_build
        with:
          cmd: build
          source: build
          artifactsDir: dist

      - name: Upload Firefox extension to AMO
        uses: browser-actions/release-firefox-addon@v0.1.3
        with:
          addon-id: ${{ secrets.FIREFOX_EXTENSION_ID }}
          addon-path: ${{ steps.firefox_build.outputs.target }}
          auth-api-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          auth-api-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Prepare for Chrome build
        run: |
          bash bin/prepare_build.sh chrome

      - name: Chrome pack extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: build
          zipFilePath: dist/OF-DL_Auth_Helper-chrome-${{ steps.chrome_version.outputs.value }}.zip

      - name: Create Chrome CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: dist/OF-DL_Auth_Helper-chrome-${{ steps.chrome_version.outputs.value }}.zip
          crxFilePath: dist/OF-DL_Auth_Helper-chrome-${{ steps.chrome_version.outputs.value }}.crx
          privateKey: ${{ secrets.CHROME_PRIVATE_KEY }}

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            dist/OF-DL_Auth_Helper-chrome-${{ steps.chrome_version.outputs.value }}.crx
            dist/OF-DL_Auth_Helper-chrome-${{ steps.chrome_version.outputs.value }}.zip
